#!/usr/bin/env bash

echo "Usage: rates EUR Sale"

t0=$(date +%s)

aws lambda invoke \
    --function-name rates \
    --payload "{\"currency\":\"$1\", \"type\":\"$2\"}" \
    --invocation-type RequestResponse \
    --region eu-west-2 \
    --log-type None \
    output.txt

t1=$(date +%s)

echo "--- Output --- Runtime: "$((t1 - t0))" seconds ---"
tput setaf 2
cat output.txt
tput sgr0
echo ""
