#!/usr/bin/env bash
rm output.txt
aws lambda invoke \
    --function-name arn:aws:lambda:eu-west-2:242867849850:function:Capitalize \
    --payload file://input.txt \
    --invocation-type RequestResponse \
    --region eu-west-2 \
    --log-type Tail \
    output.txt
echo "--- Output ---"
cat output.txt
echo ""
