#!/usr/bin/env bash

# Build artifact
echo "Building the uber jar..."
tput setaf 2
mvn clean package
tput sgr0

ZIP_FILE=fileb://target/aws-lambda-play-1.0.0.jar

function deploy {
    echo "Deploying function:"$1" to AWS using ZIP_FILE="${ZIP_FILE}
    tput setaf 3
    aws lambda update-function-code \
        --function-name $1 \
        --zip-file ${ZIP_FILE}
    tput sgr0
}

# Deploy lambdas
deploy test
deploy rates
