#!/usr/bin/env bash
echo "Building the uber jar..."
tput setaf 2
mvn clean package
tput sgr0
echo "Deloying to AWS..."
tput setaf 3
aws lambda update-function-code \
    --function-name arn:aws:lambda:eu-west-2:242867849850:function:Capitalize \
    --zip-file fileb://target/aws-lambda-play-1.0.0.jar
tput sgr0
