#!/usr/bin/env bash
mvn clean package
aws lambda update-function-code \
    --function-name arn:aws:lambda:eu-west-2:242867849850:function:Capitalize \
    --zip-file fileb://target/aws-lambda-play-1.0.0.jar
